#!/usr/bin/env python3
"""Prepare the small SVG nine-slice surfaces; app builds consume checked-in PNGs."""
import hashlib
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[2]
DEST = ROOT / 'res/projectgraph-ui'
DEST.mkdir(exist_ok=True)
palette = json.loads((ROOT / 'contrib/wine/palette.json').read_text())
manifest = {'palette_source': palette['source'], 'renderer': 'ImageMagick / librsvg 2.62.3', 'files': {}}
resources = []
for flavor, theme_offset in [('mocha', 0), ('latte', 400)]:
    colors = palette['flavors'][flavor]
    states = {
        'normal': (colors['base'], colors['surface1']),
        'hover': (colors['surface0'], colors['surface1']),
        'focus': (colors['base'], colors['mauve']),
        'disabled': (colors['base'], colors['surface0']),
        'primary': (colors['mauve'], colors['mauve']),
        'primary-hover': (colors['mauve'], colors['text']),
    }
    for kind, radius, base, state_indexes in [
        ('field', 5, 2000, range(4)), ('button', 8, 2100, range(6)),
        ('frame', 5, 2200, (0, 2, 3)),
    ]:
        for state_index in state_indexes:
            state = list(states)[state_index]
            fill, edge = states[state]
            content = f'<rect x=".5" y=".5" width="23" height="23" rx="{radius}" fill="{fill}" stroke="{edge}" stroke-width="1"/>'
            if kind == 'frame':
                content = f'''<defs><mask id="corners"><rect width="24" height="24" fill="white"/>
                <rect x=".5" y=".5" width="23" height="23" rx="5" fill="black"/></mask></defs>
                <rect width="24" height="24" fill="{colors['mantle']}" mask="url(#corners)"/>
                <rect x=".5" y=".5" width="23" height="23" rx="5" fill="none" stroke="{edge}" stroke-width="1"/>'''
            svg = DEST / f'{flavor}-{kind}-{state}.svg'
            svg.write_text(f'<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">{content}</svg>\n')
            manifest['files'][svg.name] = hashlib.sha256(svg.read_bytes()).hexdigest()
            for density, size in enumerate((24, 36, 48)):
                png = svg.with_name(svg.stem + f'-{size}.png')
                subprocess.run(['magick', '-background', 'none', '-density', '384', str(svg),
                                '-resize', f'{size}x{size}', 'PNG32:' + str(png)], check=True)
                manifest['files'][png.name] = hashlib.sha256(png.read_bytes()).hexdigest()
                resources.append(f'{base + theme_offset + state_index * 10 + density} RCDATA "../res/projectgraph-ui/{png.name}"')
(DEST / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
(DEST / 'resources.rcinc').write_text('// Prepared theme surfaces, generated by render-surfaces.py\n' + '\n'.join(resources) + '\n')
